name: sheller
description: Ergonomic scripting in Dart. Utilities for interacting with shells and converting output to Dart types. Replace your bash or python scripts with pure Dart.
version: 1.0.1
repository: https://github.com/mcmah309/sheller

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  path: ^1.8.0

platforms:
  linux:
  macos:
  windows:
