name: sheller
description: Convenience utilities for interacting with and converting shell output.
version: 0.2.0
repository: https://github.com/mcmah309/sheller

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
